[tool.poetry]
name = "numerical-collection-py"
version = "0.2.0"
description = "A collection of algorithms in numerical analysis for Python (originally implemented in C++)."
license = "Apache-2.0"
authors = ["Kenta Kabashima <kenta_program37@hotmail.co.jp>"]
readme = "README.md"
homepage = "https://gitlab.com/MusicScience37Projects/numerical-analysis/numerical-collection-py"
repository = "https://gitlab.com/MusicScience37Projects/numerical-analysis/numerical-collection-py"
documentation = "https://musicscience37projects.gitlab.io/numerical-analysis/numerical-collection-py/"
keywords = ["numerical-analysis"]
classifiers = [
    # https://pypi.org/classifiers/
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
packages = [{ include = "num_collect" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "^1.24.2"

[tool.poetry.group.dev.dependencies]
conan = "^1.59.0"
black = "^23.1.0"
click = "^8.1.3"
cmakelang = "^0.6.13"
doc8 = "^0.11.2"
myst-parser = "^1.0.0"
pre-commit = "^3.2.1"
sphinx = "^6.1.3"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.2.0"
pybind11-stubgen = "^0.13.0"
mypy = "^1.1.1"
toml = "^0.10.2"
types-toml = "^0.10.8.5"
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pydocstyle = "^6.3.0"
clang-tidy-checker = "^0.2.0"
sphinxcontrib-bibtex = "^2.5.0"
pybind11 = ">=2.10.4,<2.11.0"

[build-system]
requires = [
    "setuptools",
    "wheel",
    "toml",
    "conan>=1.59.0,<2.0",
    "pybind11>=2.10.4,<2.11.0",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pydocstyle]
convention = "google"
add-ignore = "D107"
