[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "anonfiles-directlink"
version = "1.2"
authors = [
  { name="player210", email="egorbubenov228@gmail.com" },
]
description = "Generate anonfiles direct link"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/player2I0/anonfiles-directlink"
"Bug Tracker" = "https://github.com/player2I0/anonfiles-directlink/issues"