[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "QueriPlug"
version = "1.0.3"
authors = [
  { name="Ivan Zabrodin" },
]
description = "A SQLite3 wrapper for python"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/IvanVZabrodin/QueriPlug"
