[tool.poetry]
name = "prungo-util"
version = "0.1.0"
description = "A package for basic utility functions/classes"
authors = ["c-prungo"]
packages = [{include = "prungo_util"}]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/c-prungo/prungo-util"
repository = "https://github.com/c-prungo/prungo-util"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
