[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Nondimensionalization_UssopSniperKing"
version = "0.0.2"
authors = [
  { name="UssopSniperKing"},
]
description = "A small package used to compute dimensionless numbers"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/UssopSniperKing/Nondimensionalization"
"Bug Tracker" = "https://github.com/UssopSniperKing/Nondimensionalization/issues"