[tool.poetry]
name = "bitcode"
version = "1.7"
description = "Bitcode - the ultimate library for everything Python"
authors = ["Dylan Rogers <opendylan@proton.me>"]
readme = "README.md"
homepage = "http://123web.uk/bitpy"

[tool.poetry.dependencies]
python = "^3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

