[CONFIGS]
  # OS architecture by default.
  OS_ARCH = "x86_64"
  # Where the packages download.
  # This path working only with the command download.
  DOWNLOAD_ONLY_PATH = "/tmp/slpkg/"
  # File suffix for list packages.
  # Change here if you are going to use '.sqf' files.
  FILE_LIST_SUFFIX = ".pkgs"
  # Configs for displaying colorful menu. Default is true. [true/false]
  COLORS = true
  # Dialog is a program that will let you present a variety of questions or
  # display messages using dialog boxes from a shell script.
  # Default is true. [true/false]
  DIALOG = true
  # If silent mode is true, it does not print the commands as they are executed.
  # Default is true. [true/false]
  SILENT_MODE = true
  # Choose ascii printable characters.
  # If true, it uses the extended characters, otherwise the basic ones.
  # Default is true. [true/false].
  ASCII_CHARACTERS = true
  # Set false to all the questions. If set false, option --yes will not work.
  # Default is true. [true/false].
  ASK_QUESTION = true
  # Download sources in parallel. Default is false. [true/false]
  PARALLEL_DOWNLOADS = false
  # Pass your file pattern here, if you want to work only with 'sbo' packages
  # add '*_SBo' pattern. Default is the '*'.
  FILE_PATTERN = "*"
  # There are 5 predefined spinners for the progress bar.
  # Default is pixel. [spinner/pie/moon/line/pixel]
  PROGRESS_SPINNER = "pixel"
  # Choose color for the progress bar spinner.
  # Default is green. [green/violet/yellow/blue/cyan/grey/red]
  SPINNER_COLOR = "green"

  # Slackware command for install packages, instead, you can use 'installpkg'.
  INSTALLPKG = "upgradepkg --install-new"
  # Slackware command to reinstall packages.
  REINSTALL = "upgradepkg --reinstall"
  # Slackware command to remove packages.
  REMOVEPKG = "removepkg"

  # You can choose a downloader among wget, curl and lftp.
  # Default is wget. [wget/curl/lftp]
  DOWNLOADER = "wget"
  # Wget downloader options.
  # -c, --continue: resume getting a partially-downloaded file.
  # -q, Turn off Wget's output.
  # --show-progress, Force wget to display the progress bar in any verbosity.
  WGET_OPTIONS = "-c -q --progress=bar:force:noscroll --show-progress"
  # Curl downloader options.
  CURL_OPTIONS = ""
  # Lftp donwloader options.
  LFTP_GET_OPTIONS = "-c get -e"
  # Lftp mirror options are used to synchronize with the repositories.
  LFTP_MIRROR_OPTIONS = "-c mirror --parallel=100 --only-newer"
