[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "pspsmgen"
version = "0.0.2"
authors = [
  { name="ronaldohj", email="ronaldohj@hotmail.com" },
]
description = "Pspsmgen is a 3d pore-scale Pre-Salt model generator to simulate	petrophysical properties."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/ronaldohj/pspsmgen"