[tool.poetry]
name = "yaml-scripts"
version = "0.1.1"
description = "Creating windows auto install scripts from YAML config files"
authors = ["arnos-stuff <bcda0276@gmail.com>"]
readme = "README.md"
packages = [{include = "yaml_scripts"}]
homepage = "https://github.com/arnos-stuff/yaml-scripts"

[tool.poetry.dependencies]
python = "^3.9"
yaml-setup = "^0.1.1"
ix-cli = "^0.1.2"

[tool.poetry.scripts]
yamlrun = "yaml_scripts.cli:app"
ymlr = "yaml_scripts.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
