[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "playtour"
version = "0.0.3"
authors = [
  { name="ken", email="block24block@gmail.com" },
]
description = "Loop page with playwright"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "playwright",
]

[project.urls]
"Homepage" = "https://github.com/turnon/playtour"
"Bug Tracker" = "https://github.com/turnon/playtour/issues"