[tool.poetry]
name = "dockyard-cli"
version = "0.1.14"
description = "CLI for dockyard"
authors = ["rsingh <rsingh@altoslabs.com>"]
readme = "README.md"

[tool.poetry.scripts]
dcli = "dockyard_cli.main:main"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
requests = "^2.28.1"
webdriver-setup = "^1.1.0"
selenium = "^4.7.2"
tabulate = "^0.9.0"
rich = "^13.3.3"
sseclient-py = "^1.7.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
