[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qqg"
version = "0.0.1"
authors = [
  { name="Emil Kloeden", email="emilkloeden@gmail.com" },
]
description = "A small CLI search tool"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["beautifulsoup4==4.12.2","requests==2.28.2", "markdownify==0.11.6"]

[project.urls]
"Homepage" = "https://github.com/emilkloeden/qqg"
"Bug Tracker" = "https://github.com/emilkloeden/qqg/issues"

[project.scripts]
search = "qqg.search:main"