[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scraper2_hj3415"
version = "0.3.7"
authors = [
  { name="Hyungjin Kim", email="hj3415@gmail.com" },
]
description = "Gathering the stock data"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "scrapy>=2.8.0",
    "pandas>=1.5.3",
    "sqlalchemy>=2.0.4",
    "selenium>=4.8.2",
    "lxml>=4.9.2",
    "util_hj3415>=0.9.6",
    "analyser_hj3415>=0.3.5",
]

# cli script 만드는 방법
# https://hatch.pypa.io/latest/config/metadata/
# https://dev.to/thefern/argparse-and-script-entry-points-4cde
[project.scripts]
nfscraper = "scraper2_hj3415.cli:nfscraper"
miscraper = "scraper2_hj3415.cli:miscraper"

[project.urls]
"Homepage" = "https://pypi.org/project/scraper2_hj3415/"
"Bug Tracker" = "https://pypi.org/project/scraper2_hj3415/"