[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "bcligpt"
version = "0.1.4"
description = "Better CLI for GPT-3.5"
dependencies = [
    "openai", "tiktoken"
]
readme = "README.md"
authors = [
    { name = "Marco Filippozzi", email = "marco.filippozzi98@gmail.com" }
    ]
[project.scripts]
bcligpt = "bcligpt:start"
