[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "generateNscore"
version = "1.0.5"
authors = [
  { name="Sukmock Lee", email="smlee@inha.ac.kr" },
]
description = "A package to generate question sheets in HTML files and to score answers in text files"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Topic :: Education :: Testing",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Education",
    "Intended Audience :: End Users/Desktop"
]

[project.urls]
"Homepage" = "https://github.com/generateNscore/generateNscore"
"Bug Tracker" = "https://github.com/generateNscore/generateNscore/issues"